<template>
  <div>
    <div style="float: left">
      <sc-select allow-create :data='data' @change="Change" :multiple-limit="multipleLimit"
                 show-checkbox
                 :default-checked="defaultChecked"
                 :default-props="defaultProps"
                 clearable filterable></sc-select>
      <el-button @click="setModel">赋值</el-button>
    </div>
  </div>

</template>

<script>
  export default {
    data() {
      return {
        defaultChecked: '',
        multipleLimit: 0,
        selectVal: '',
       /* data: [{
          "ddKey": "00088009",
          "ddName": "资金划拨",
          "ddOrder": "1",
          "extendValue": "",
          "extendValue2": "",
          "letter": "zjhb",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088019",
          "ddName": "调入中债",
          "ddOrder": "2",
          "extendValue": "00014003",
          "extendValue2": "",
          "letter": "drzz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088020",
          "ddName": "调入上清",
          "ddOrder": "3",
          "extendValue": "00014003",
          "extendValue2": "",
          "letter": "drsq",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088021",
          "ddName": "中债调出",
          "ddOrder": "4",
          "extendValue": "00014003",
          "extendValue2": "",
          "letter": "zzdc",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088022",
          "ddName": "上清调出",
          "ddOrder": "5",
          "extendValue": "00014003",
          "extendValue2": "",
          "letter": "sqdc",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088038",
          "ddName": "中债转上清",
          "ddOrder": "6",
          "extendValue": "",
          "extendValue2": "",
          "letter": "zzzsq",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088003",
          "ddName": "同业存单",
          "ddOrder": "7",
          "extendValue": "",
          "extendValue2": "",
          "letter": "tycd",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088110",
          "ddName": "付债券分销费",
          "ddOrder": "8",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fzqfxf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088004",
          "ddName": "债券分销",
          "ddOrder": "9",
          "extendValue": "",
          "extendValue2": "",
          "letter": "zqfx",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088005",
          "ddName": "资金追加",
          "ddOrder": "10",
          "extendValue": "",
          "extendValue2": "",
          "letter": "zjzj",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088006",
          "ddName": "资金提取",
          "ddOrder": "11",
          "extendValue": "",
          "extendValue2": "",
          "letter": "zjtq",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088015",
          "ddName": "付外汇中心费用",
          "ddOrder": "12",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fwhzxfy",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088017",
          "ddName": "付中债登费用",
          "ddOrder": "13",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fzzdfy",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088056",
          "ddName": "付上清所其他费用",
          "ddOrder": "14",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fsqsqtfy",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088016",
          "ddName": "付上清所全额结算业务费用",
          "ddOrder": "14",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fsqsqejsywfy",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088011",
          "ddName": "付管理费",
          "ddOrder": "15",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fglf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088105",
          "ddName": "付管理风险准备金",
          "ddOrder": "16",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fglfxzbj",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088012",
          "ddName": "付托管费",
          "ddOrder": "17",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ftgf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088007",
          "ddName": "付托管风险准备金",
          "ddOrder": "18",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ftgfxzbj",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088014",
          "ddName": "付券商佣金",
          "ddOrder": "19",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fqsyj",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088008",
          "ddName": "付受托费",
          "ddOrder": "20",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fstf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088013",
          "ddName": "付销售服务费",
          "ddOrder": "21",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fxsfwf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088023",
          "ddName": "付业绩报酬",
          "ddOrder": "22",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fyjbc",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088024",
          "ddName": "付业绩报酬风险准备金",
          "ddOrder": "23",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fyjbcfxzbj",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088028",
          "ddName": "付信息披露费-证券日报",
          "ddOrder": "24",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fxxplf-zqrb",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088037",
          "ddName": "付信息披露费-证券时报",
          "ddOrder": "25",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fxxplf-zqsb",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088036",
          "ddName": "付信息披露费-中证报",
          "ddOrder": "26",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fxxplf-zzb",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088029",
          "ddName": "付信息披露费-上证报",
          "ddOrder": "27",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fxxplf-szb",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088039",
          "ddName": "付指数使用费",
          "ddOrder": "28",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fzssyf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088041",
          "ddName": "付代理费和信息服务费",
          "ddOrder": "30",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fdlfhxxfwf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088042",
          "ddName": "付基金现金分红款",
          "ddOrder": "31",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fjjxjfhk",
          "pddKey": "00151005"
        }, {
          "ddKey": "00088043",
          "ddName": "付分红手续费",
          "ddOrder": "32",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ffhsxf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088044",
          "ddName": "付开户费",
          "ddOrder": "33",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fkhf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088045",
          "ddName": "付担保费",
          "ddOrder": "34",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fdbf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088025",
          "ddName": "付律师费",
          "ddOrder": "35",
          "extendValue": "",
          "extendValue2": "",
          "letter": "flsf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088026",
          "ddName": "付上市年费",
          "ddOrder": "36",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fssnf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088027",
          "ddName": "付审计费",
          "ddOrder": "37",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fsjf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088046",
          "ddName": "付增值税",
          "ddOrder": "38",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fzzs",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088127",
          "ddName": "付增值附加税",
          "ddOrder": "38.1",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fzzfjs",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088134",
          "ddName": "付增值及附加税",
          "ddOrder": "38.2",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fzzjfjs",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088128",
          "ddName": "付增值附加税_城建费",
          "ddOrder": "38.3",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fzzfjs_cjf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088129",
          "ddName": "付增值附加税_地方教育费",
          "ddOrder": "38.4",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fzzfjs_dfjyf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088130",
          "ddName": "付增值附加税_教育费",
          "ddOrder": "38.5",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fzzfjs_jyf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088131",
          "ddName": "付增值附加税_堤防维护费",
          "ddOrder": "38.6",
          "extendValue": "00084020",
          "extendValue2": "",
          "letter": "fzzfjs_dfwhf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088047",
          "ddName": "付邮寄费",
          "ddOrder": "39",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fyjf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088048",
          "ddName": "付指令处理费",
          "ddOrder": "40",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fzlclf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088050",
          "ddName": "付汇划费",
          "ddOrder": "42",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fhhf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088051",
          "ddName": "付保本风险金",
          "ddOrder": "43",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fbbfxj",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088052",
          "ddName": "付超额管理费",
          "ddOrder": "44",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fceglf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088053",
          "ddName": "付财务顾问费",
          "ddOrder": "45",
          "extendValue": "",
          "extendValue2": "",
          "letter": "fcwgwf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088054",
          "ddName": "付投资顾问费",
          "ddOrder": "46",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ftzgwf",
          "pddKey": "00151004"
        }, {
          "ddKey": "00088018",
          "ddName": "TA轧差款",
          "ddOrder": "47",
          "extendValue": "",
          "extendValue2": "",
          "letter": "TAyck",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088010",
          "ddName": "TA赎回款",
          "ddOrder": "48",
          "extendValue": "",
          "extendValue2": "",
          "letter": "TAshk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088055",
          "ddName": "TA转出款",
          "ddOrder": "49",
          "extendValue": "",
          "extendValue2": "",
          "letter": "TAzck",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088113",
          "ddName": "上海中登TA申购款",
          "ddOrder": "54",
          "extendValue": "",
          "extendValue2": "",
          "letter": "shzdTAsgk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088114",
          "ddName": "上海中登TA赎回款",
          "ddOrder": "55",
          "extendValue": "",
          "extendValue2": "",
          "letter": "shzdTAshk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088115",
          "ddName": "上海中登TA轧差款",
          "ddOrder": "56",
          "extendValue": "",
          "extendValue2": "",
          "letter": "shzdTAyck",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088116",
          "ddName": "上海中登TA转出款",
          "ddOrder": "57",
          "extendValue": "",
          "extendValue2": "",
          "letter": "shzdTAzck",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088117",
          "ddName": "上海中登TA转入款",
          "ddOrder": "58",
          "extendValue": "",
          "extendValue2": "",
          "letter": "shzdTAzrk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088120",
          "ddName": "深圳中登TA申购款",
          "ddOrder": "59",
          "extendValue": "",
          "extendValue2": "",
          "letter": "szzdTAsgk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088121",
          "ddName": "深圳中登TA赎回款",
          "ddOrder": "60",
          "extendValue": "",
          "extendValue2": "",
          "letter": "szzdTAshk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088122",
          "ddName": "深圳中登TA轧差款",
          "ddOrder": "61",
          "extendValue": "",
          "extendValue2": "",
          "letter": "szzdTAyck",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088123",
          "ddName": "深圳中登TA转出款",
          "ddOrder": "62",
          "extendValue": "",
          "extendValue2": "",
          "letter": "szzdTAzck",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088124",
          "ddName": "深圳中登TA转入款",
          "ddOrder": "63",
          "extendValue": "",
          "extendValue2": "",
          "letter": "szzdTAzrk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088061",
          "ddName": "ETF退补和现金差额轧差出款",
          "ddOrder": "68",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ETFtbhxjceycck",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088062",
          "ddName": "ETF现金差额出款",
          "ddOrder": "69",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ETFxjceck",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088063",
          "ddName": "ETF现金替代款退款",
          "ddOrder": "70",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ETFxjtdktk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088064",
          "ddName": "联接基金退补和现金差额出款",
          "ddOrder": "71",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ljjjtbhxjceck",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088065",
          "ddName": "联接基金现金差额出款",
          "ddOrder": "72",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ljjjxjceck",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088066",
          "ddName": "联接基金现金替代款退款",
          "ddOrder": "73",
          "extendValue": "",
          "extendValue2": "",
          "letter": "ljjjxjtdktk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088067",
          "ddName": "金交所入金",
          "ddOrder": "74",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jjsrj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088068",
          "ddName": "金交所出金",
          "ddOrder": "75",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jjscj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088069",
          "ddName": "金交所入金_银转金",
          "ddOrder": "76",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jjsrj_yzj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088070",
          "ddName": "金交所出金_金转银",
          "ddOrder": "77",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jjscj_jzy",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088071",
          "ddName": "期货入金",
          "ddOrder": "78",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qhrj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088072",
          "ddName": "期货出金",
          "ddOrder": "79",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qhcj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088073",
          "ddName": "券商入金",
          "ddOrder": "80",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qsrj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088074",
          "ddName": "券商出金",
          "ddOrder": "81",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qscj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088075",
          "ddName": "融资融券入金",
          "ddOrder": "82",
          "extendValue": "",
          "extendValue2": "",
          "letter": "rzrqrj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088076",
          "ddName": "融资融券出金",
          "ddOrder": "83",
          "extendValue": "",
          "extendValue2": "",
          "letter": "rzrqcj",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088077",
          "ddName": "期货入金_银转期",
          "ddOrder": "84",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qhrj_yzq",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088078",
          "ddName": "期货出金_期转银",
          "ddOrder": "85",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qhcj_qzy",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088079",
          "ddName": "券商入金_银转证",
          "ddOrder": "86",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qsrj_yzz",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088080",
          "ddName": "券商出金_证转银",
          "ddOrder": "87",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qscj_zzy",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088081",
          "ddName": "融资融券入金_银转证",
          "ddOrder": "88",
          "extendValue": "",
          "extendValue2": "",
          "letter": "rzrqrj_yzz",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088082",
          "ddName": "融资融券出金_证转银",
          "ddOrder": "89",
          "extendValue": "",
          "extendValue2": "",
          "letter": "rzrqcj_zzy",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088083",
          "ddName": "外汇交易-购汇",
          "ddOrder": "90",
          "extendValue": "",
          "extendValue2": "",
          "letter": "whjy-gh",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088084",
          "ddName": "外汇交易-结汇",
          "ddOrder": "91",
          "extendValue": "",
          "extendValue2": "",
          "letter": "whjy-jh",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088085",
          "ddName": "境内外资金划拨",
          "ddOrder": "92",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jnwzjhb",
          "pddKey": "00151001"
        }, {
          "ddKey": "00088001",
          "ddName": "定期存款投资",
          "ddOrder": "93",
          "extendValue": "",
          "extendValue2": "",
          "letter": "dqcktz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088086",
          "ddName": "通知存款投资",
          "ddOrder": "94",
          "extendValue": "",
          "extendValue2": "",
          "letter": "tzcktz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088002",
          "ddName": "协议存款投资",
          "ddOrder": "95",
          "extendValue": "",
          "extendValue2": "",
          "letter": "xycktz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088087",
          "ddName": "保险投资",
          "ddOrder": "96",
          "extendValue": "",
          "extendValue2": "",
          "letter": "bxtz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088088",
          "ddName": "信托投资",
          "ddOrder": "97",
          "extendValue": "",
          "extendValue2": "",
          "letter": "xttz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088089",
          "ddName": "期权投资",
          "ddOrder": "98",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qqtz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088090",
          "ddName": "债权投资",
          "ddOrder": "99",
          "extendValue": "",
          "extendValue2": "",
          "letter": "zqtz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088035",
          "ddName": "开放式基金认购款",
          "ddOrder": "100",
          "extendValue": "",
          "extendValue2": "",
          "letter": "kfsjjrgk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088034",
          "ddName": "开放式基金申购款",
          "ddOrder": "101",
          "extendValue": "",
          "extendValue2": "",
          "letter": "kfsjjsgk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088106",
          "ddName": "开放式基金赎回款",
          "ddOrder": "102",
          "extendValue": "",
          "extendValue2": "",
          "letter": "kfsjjshk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088091",
          "ddName": "开放式基金红利到账",
          "ddOrder": "103",
          "extendValue": "",
          "extendValue2": "",
          "letter": "kfsjjhldz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088092",
          "ddName": "集合理财认购款",
          "ddOrder": "104",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jhlcrgk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088093",
          "ddName": "集合理财申购款",
          "ddOrder": "105",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jhlcsgk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088094",
          "ddName": "集合理财赎回款",
          "ddOrder": "106",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jhlcshk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088095",
          "ddName": "集合理财红利到账",
          "ddOrder": "107",
          "extendValue": "",
          "extendValue2": "",
          "letter": "jhlchldz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088032",
          "ddName": "网下新股申购_上海",
          "ddOrder": "108",
          "extendValue": "",
          "extendValue2": "",
          "letter": "wxxgsg_sh",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088033",
          "ddName": "网下新股申购_深圳",
          "ddOrder": "109",
          "extendValue": "",
          "extendValue2": "",
          "letter": "wxxgsg_sz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088096",
          "ddName": "股票定向增发_上海",
          "ddOrder": "110",
          "extendValue": "",
          "extendValue2": "",
          "letter": "gpdxzf_sh",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088097",
          "ddName": "股票定向增发_深圳",
          "ddOrder": "111",
          "extendValue": "",
          "extendValue2": "",
          "letter": "gpdxzf_sz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088098",
          "ddName": "网下新股增发_上海",
          "ddOrder": "112",
          "extendValue": "",
          "extendValue2": "",
          "letter": "wxxgzf_sh",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088099",
          "ddName": "网下新股增发_深圳",
          "ddOrder": "113",
          "extendValue": "",
          "extendValue2": "",
          "letter": "wxxgzf_sz",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088030",
          "ddName": "其他付费",
          "ddOrder": "122",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qtff",
          "pddKey": "00151005"
        }, {
          "ddKey": "00088031",
          "ddName": "其他付款",
          "ddOrder": "123",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qtfk",
          "pddKey": "00151005"
        }, {
          "ddKey": "00088104",
          "ddName": "其他收款",
          "ddOrder": "124",
          "extendValue": "",
          "extendValue2": "",
          "letter": "qtsk",
          "pddKey": "00151005"
        }, {
          "ddKey": "00088125",
          "ddName": "网下新债申购",
          "ddOrder": "125",
          "extendValue": "",
          "extendValue2": "",
          "letter": "wxxzsg",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088126",
          "ddName": "同业存单_认购",
          "ddOrder": "126",
          "extendValue": "",
          "extendValue2": "",
          "letter": "tycd_rg",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088132",
          "ddName": "T+0轧差付款_上海",
          "ddOrder": "132",
          "extendValue": "",
          "extendValue2": "",
          "letter": "T+0ycfk_sh",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088133",
          "ddName": "T+0轧差付款_深圳",
          "ddOrder": "132.1",
          "extendValue": "",
          "extendValue2": "",
          "letter": "T+0ycfk_sz",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088135",
          "ddName": "T+0轧差收款_上海",
          "ddOrder": "132.3",
          "extendValue": "",
          "extendValue2": "",
          "letter": "T+0ycsk_sh",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088136",
          "ddName": "T+0轧差收款_深圳",
          "ddOrder": "132.4",
          "extendValue": "",
          "extendValue2": "",
          "letter": "T+0ycsk_sz",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088111",
          "ddName": "上海RTGS交易逐笔_付款",
          "ddOrder": "132.5",
          "extendValue": "",
          "extendValue2": "",
          "letter": "shRTGSjyzb_fk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088112",
          "ddName": "上海RTGS交易逐笔_收款",
          "ddOrder": "132.6",
          "extendValue": "",
          "extendValue2": "",
          "letter": "shRTGSjyzb_sk",
          "pddKey": "00151002"
        }, {
          "ddKey": "00088137",
          "ddName": "深圳RTGS交易逐笔_付款",
          "ddOrder": "132.7",
          "extendValue": "",
          "extendValue2": "",
          "letter": "szRTGSjyzb_fk",
          "pddKey": "00151003"
        }, {
          "ddKey": "00088138",
          "ddName": "深圳RTGS交易逐笔_收款",
          "ddOrder": "132.8",
          "extendValue": "",
          "extendValue2": "",
          "letter": "szRTGSjyzb_sk",
          "pddKey": "00151003"
        }],*/
       data: [{
         value: '选项1',
         label: '黄金糕'
       }, {
         value: '选项2',
         label: '双皮奶'
       }, {
         value: '选项3',
         label: '蚵仔煎'
       }, {
         value: '选项4',
         label: '龙须面'
       }, {
         value: '选项5',
         label: '北京烤鸭'
       }],
        defaultProps: {
          label: 'label',
          nodeKey: 'value'
        }
      };
    },
    watch: {
      selectVal(val) {
        console.log('--watcth----');
        console.log(val);
      }
    },
    methods: {
      Change(node, all) {
        console.log(node);
      },
      Clear() {
        // this.defaultChecked = [];
      },
      Btn() {
        this.defaultChecked = [];
      },
      setModel() {
        this.selectVal = '';
        // this.selectVal = '00088016,00088011';
      }
    },
    created() {
      this.defaultChecked = ['选项1','选项2'];
      // axios.get('../JsonData/test.json', {}).then((response) => {
      //     var data = response.data;
      //     _this.defaultChecked = ['l3DAQKdq', 'Cq2SViA'];
      //     // _this.$nextTick(() => {
      //     //	_this.defaultChecked = ['l3DAQKdq', 'Cq2SViA'];
      //     // });
      // });
    },
    mounted() {
      // this.defaultChecked = ['00088009','00088019','00088020'];
      // this.selectVal = '00088009,00088019,00088020';
      // this.$nextTick(function() {
      //   this.selectVal = this.data.map(function (item) {
      //     return item.value;
      //   }).join(',');
      // 	// this.defaultChecked  =['选项4']
      // });
    }
  };
</script>

<style>
</style>